Description: Configuration for Adapter participant for SIL Kit Adapter QEMU (qmp) demo
ParticipantName: sil-kit-adapter-qemu
Middleware:
  RegistryUri: silkit://localhost:8501  
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
